/*
 *   Copyright (c) 2024 Cameron Dudd
 *   All rights reserved.
 */

#include "piece.h"

#include <unity.h>
#include <unity_fixture.h>

TEST_GROUP(pieceTests);

TEST_SETUP(pieceTests) {}

TEST_TEAR_DOWN(pieceTests) {}

TEST(pieceTests, pieceDefinitions) {
  TEST_ASSERT_EQUAL_UINT8(0, PIECE_NULL);
  TEST_ASSERT_EQUAL_UINT8(1, PIECE_WHITE);
  TEST_ASSERT_EQUAL_UINT8(2, PIECE_BLACK);
  TEST_ASSERT_EQUAL_UINT8(4, PIECE_PAWN);
  TEST_ASSERT_EQUAL_UINT8(8, PIECE_KNIGHT);
  TEST_ASSERT_EQUAL_UINT8(16, PIECE_BISHOP);
  TEST_ASSERT_EQUAL_UINT8(32, PIECE_ROOK);
  TEST_ASSERT_EQUAL_UINT8(64, PIECE_QUEEN);
  TEST_ASSERT_EQUAL_UINT8(128, PIECE_KING);
  TEST_ASSERT_EQUAL_UINT8(5, PIECE_WHITE | PIECE_PAWN);
  TEST_ASSERT_EQUAL_UINT8(9, PIECE_WHITE | PIECE_KNIGHT);
  TEST_ASSERT_EQUAL_UINT8(17, PIECE_WHITE | PIECE_BISHOP);
  TEST_ASSERT_EQUAL_UINT8(33, PIECE_WHITE | PIECE_ROOK);
  TEST_ASSERT_EQUAL_UINT8(65, PIECE_WHITE | PIECE_QUEEN);
  TEST_ASSERT_EQUAL_UINT8(129, PIECE_WHITE | PIECE_KING);
  TEST_ASSERT_EQUAL_UINT8(6, PIECE_BLACK | PIECE_PAWN);
  TEST_ASSERT_EQUAL_UINT8(10, PIECE_BLACK | PIECE_KNIGHT);
  TEST_ASSERT_EQUAL_UINT8(18, PIECE_BLACK | PIECE_BISHOP);
  TEST_ASSERT_EQUAL_UINT8(34, PIECE_BLACK | PIECE_ROOK);
  TEST_ASSERT_EQUAL_UINT8(66, PIECE_BLACK | PIECE_QUEEN);
  TEST_ASSERT_EQUAL_UINT8(130, PIECE_BLACK | PIECE_KING);
}

TEST_GROUP_RUNNER(pieceTests) { RUN_TEST_CASE(pieceTests, pieceDefinitions); }
